name: Terraform Infra

on: workflow_dispatch
  # push:
  #   branches:
  #   - main
  #   - feature/**
  # pull_request:
  #   branches:
  #   - main
  #   - feature/**

jobs:
  terraformsetup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
        
      - name: Hello World
        run: echo "Hello World"
        
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Terraform Init
        run: terraform init



