name: Terraform Infra

on: workflow_dispatch
  # push:
  #   branches:
  #   - main
  #   - feature/**
  # pull_request:
  #   branches:
  #   - main
  #   - feature/**
permissions:
  id-token: write
  contents: read
  
jobs:
  terraformsetup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
        
      - name: Azure login
        uses: Azure/login@v2.3.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
        
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Terraform Init & Plan
        run: |
          terraform init
          terraform plan --var-file=env-dev.tfvars -out=tfplan
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v6.0.0
        with:
          name: tfplan
          path: tfplan

  TFScan:
    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write
    runs-on: ubuntu-latest
    # needs: terraformsetup
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Super-linter
        uses: super-linter/super-linter@v8.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.JKGITHUB_TOKEN }}



